import type { FormationData, PlayerCardData, Position, Rarity } from './types';

export const rarityMeta: Record<Rarity, { name: string; color: number; glow: number; minRating: number }> = {
  bronze: { name: '铜卡', color: 0xa86632, glow: 0xffb071, minRating: 62 },
  silver: { name: '银卡', color: 0xb9c2cf, glow: 0xf2f7ff, minRating: 72 },
  gold: { name: '金卡', color: 0xffc43b, glow: 0xfff0a8, minRating: 82 },
  purple: { name: '紫卡', color: 0x9b45ff, glow: 0xe0b2ff, minRating: 88 },
  orange: { name: '橙卡', color: 0xff7a1a, glow: 0xffc18a, minRating: 93 },
  legend: { name: '传奇', color: 0xffe06b, glow: 0xffffff, minRating: 94 }
};

const portraits = {
  mbappe: '/assets/players/generated/mbappe.png',
  haaland: '/assets/players/generated/haaland.png',
  messi: '/assets/players/generated/messi.png',
  cr7: '/assets/players/generated/cr7.png',
  vini: '/assets/players/generated/vini.png',
  dembele: '/assets/players/generated/dembele.png',
  salah: '/assets/players/generated/salah.png',
  kane: '/assets/players/generated/kane.png',
  yamal: '/assets/players/generated/yamal.png',
  pele: '/assets/players/generated/pele.png',
  maradona: '/assets/players/generated/maradona.png',
  ronaldo: '/assets/players/generated/ronaldo.png',
  cruyff: '/assets/players/generated/cruyff.png',
  neymar: '/assets/players/generated/neymar.png',
  son: '/assets/players/generated/son.png',
  griezmann: '/assets/players/generated/griezmann.png',
  bellingham: '/assets/players/generated/bellingham.png',
  rodri: '/assets/players/generated/rodri.png',
  debruyne: '/assets/players/generated/debruyne.png',
  pedri: '/assets/players/generated/pedri.png',
  wirtz: '/assets/players/generated/wirtz.png',
  modric: '/assets/players/generated/modric.png',
  zidane: '/assets/players/generated/zidane.png',
  xavi: '/assets/players/generated/xavi.png',
  iniesta: '/assets/players/generated/iniesta.png',
  ronaldinho: '/assets/players/generated/ronaldinho.png',
  vandijk: '/assets/players/generated/vandijk.png',
  saliba: '/assets/players/generated/saliba.png',
  hakimi: '/assets/players/generated/hakimi.png',
  dias: '/assets/players/generated/dias.png',
  maldini: '/assets/players/generated/maldini.png',
  carlos: '/assets/players/generated/carlos.png',
  courtois: '/assets/players/generated/courtois.png',
  donnarumma: '/assets/players/generated/donnarumma.png',
  neuer: '/assets/players/generated/neuer.png',
  buffon: '/assets/players/generated/buffon.png',
  alisson: '/assets/players/generated/alisson.png',
  ederson: '/assets/players/generated/ederson.png',
  casillas: '/assets/players/generated/casillas.png',
  yashin: '/assets/players/generated/yashin.png',
  ramos: '/assets/players/generated/ramos.png',
  trent: '/assets/players/generated/trent.png',
  davies: '/assets/players/generated/davies.png',
  kimmich: '/assets/players/generated/kimmich.png',
  suarez: '/assets/players/generated/suarez.png',
  lewandowski: '/assets/players/generated/lewandowski.png',
  benzema: '/assets/players/generated/benzema.png',
  zlatan: '/assets/players/generated/zlatan.png',
  saka: '/assets/players/generated/saka.png',
  foden: '/assets/players/generated/foden.png',
  lautaro: '/assets/players/generated/lautaro.png',
  osimhen: '/assets/players/generated/osimhen.png',
  kvaratskhelia: '/assets/players/generated/kvaratskhelia.png',
  nunez: '/assets/players/generated/nunez.png',
  leao: '/assets/players/generated/leao.png',
  pulisic: '/assets/players/generated/pulisic.png',
  raphinha: '/assets/players/generated/raphinha.png',
  luisDiaz: '/assets/players/generated/luis-diaz.png',
  isak: '/assets/players/generated/isak.png',
  vlahovic: '/assets/players/generated/vlahovic.png',
  gakpo: '/assets/players/generated/gakpo.png',
  olise: '/assets/players/generated/olise.png',
  nicoWilliams: '/assets/players/generated/nico-williams.png',
  kubo: '/assets/players/generated/kubo.png',
  mitoma: '/assets/players/generated/mitoma.png',
  musiala: '/assets/players/generated/musiala.png',
  odegaard: '/assets/players/generated/odegaard.png',
  valverde: '/assets/players/generated/valverde.png',
  rice: '/assets/players/generated/rice.png',
  gavi: '/assets/players/generated/gavi.png',
  enzo: '/assets/players/generated/enzo.png',
  macAllister: '/assets/players/generated/mac-allister.png',
  brunoFernandes: '/assets/players/generated/bruno-fernandes.png',
  bernardoSilva: '/assets/players/generated/bernardo-silva.png',
  chiesa: '/assets/players/generated/chiesa.png',
  barella: '/assets/players/generated/barella.png',
  camavinga: '/assets/players/generated/camavinga.png',
  tchouameni: '/assets/players/generated/tchouameni.png',
  rudiger: '/assets/players/generated/rudiger.png',
  militao: '/assets/players/generated/militao.png',
  theo: '/assets/players/generated/theo.png',
  cancelo: '/assets/players/generated/cancelo.png',
  kounde: '/assets/players/generated/kounde.png',
  upamecano: '/assets/players/generated/upamecano.png',
  gvardiol: '/assets/players/generated/gvardiol.png',
  kimMinjae: '/assets/players/generated/kim-minjae.png',
  maignan: '/assets/players/generated/maignan.png',
  emiliano: '/assets/players/generated/emiliano.png'
};

export const formations: FormationData[] = [
  {
    id: '4231',
    name: '4-2-3-1',
    style: '平衡',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.18, y: 0.72 },
      { id: 'df2', position: 'DF', x: 0.38, y: 0.7 },
      { id: 'df3', position: 'DF', x: 0.62, y: 0.7 },
      { id: 'df4', position: 'DF', x: 0.82, y: 0.72 },
      { id: 'mf1', position: 'MF', x: 0.36, y: 0.54 },
      { id: 'mf2', position: 'MF', x: 0.64, y: 0.54 },
      { id: 'mf3', position: 'MF', x: 0.2, y: 0.36 },
      { id: 'mf4', position: 'MF', x: 0.5, y: 0.32 },
      { id: 'mf5', position: 'MF', x: 0.8, y: 0.36 },
      { id: 'fw', position: 'FW', x: 0.5, y: 0.16 }
    ]
  },
  {
    id: '433',
    name: '4-3-3',
    style: '进攻',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.18, y: 0.72 },
      { id: 'df2', position: 'DF', x: 0.38, y: 0.7 },
      { id: 'df3', position: 'DF', x: 0.62, y: 0.7 },
      { id: 'df4', position: 'DF', x: 0.82, y: 0.72 },
      { id: 'mf1', position: 'MF', x: 0.28, y: 0.48 },
      { id: 'mf2', position: 'MF', x: 0.5, y: 0.45 },
      { id: 'mf3', position: 'MF', x: 0.72, y: 0.48 },
      { id: 'fw1', position: 'FW', x: 0.22, y: 0.18 },
      { id: 'fw2', position: 'FW', x: 0.5, y: 0.13 },
      { id: 'fw3', position: 'FW', x: 0.78, y: 0.18 }
    ]
  },
  {
    id: '532',
    name: '5-3-2',
    style: '防守',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.12, y: 0.72 },
      { id: 'df2', position: 'DF', x: 0.3, y: 0.68 },
      { id: 'df3', position: 'DF', x: 0.5, y: 0.66 },
      { id: 'df4', position: 'DF', x: 0.7, y: 0.68 },
      { id: 'df5', position: 'DF', x: 0.88, y: 0.72 },
      { id: 'mf1', position: 'MF', x: 0.28, y: 0.45 },
      { id: 'mf2', position: 'MF', x: 0.5, y: 0.42 },
      { id: 'mf3', position: 'MF', x: 0.72, y: 0.45 },
      { id: 'fw1', position: 'FW', x: 0.38, y: 0.17 },
      { id: 'fw2', position: 'FW', x: 0.62, y: 0.17 }
    ]
  },
  {
    id: '442',
    name: '4-4-2',
    style: '经典',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.18, y: 0.72 },
      { id: 'df2', position: 'DF', x: 0.38, y: 0.7 },
      { id: 'df3', position: 'DF', x: 0.62, y: 0.7 },
      { id: 'df4', position: 'DF', x: 0.82, y: 0.72 },
      { id: 'mf1', position: 'MF', x: 0.18, y: 0.46 },
      { id: 'mf2', position: 'MF', x: 0.38, y: 0.5 },
      { id: 'mf3', position: 'MF', x: 0.62, y: 0.5 },
      { id: 'mf4', position: 'MF', x: 0.82, y: 0.46 },
      { id: 'fw1', position: 'FW', x: 0.38, y: 0.18 },
      { id: 'fw2', position: 'FW', x: 0.62, y: 0.18 }
    ]
  },
  {
    id: '352',
    name: '3-5-2',
    style: '控场',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.28, y: 0.7 },
      { id: 'df2', position: 'DF', x: 0.5, y: 0.68 },
      { id: 'df3', position: 'DF', x: 0.72, y: 0.7 },
      { id: 'mf1', position: 'MF', x: 0.14, y: 0.5 },
      { id: 'mf2', position: 'MF', x: 0.34, y: 0.48 },
      { id: 'mf3', position: 'MF', x: 0.5, y: 0.42 },
      { id: 'mf4', position: 'MF', x: 0.66, y: 0.48 },
      { id: 'mf5', position: 'MF', x: 0.86, y: 0.5 },
      { id: 'fw1', position: 'FW', x: 0.38, y: 0.18 },
      { id: 'fw2', position: 'FW', x: 0.62, y: 0.18 }
    ]
  },
  {
    id: '343',
    name: '3-4-3',
    style: '压迫',
    slots: [
      { id: 'gk', position: 'GK', x: 0.5, y: 0.9 },
      { id: 'df1', position: 'DF', x: 0.28, y: 0.7 },
      { id: 'df2', position: 'DF', x: 0.5, y: 0.68 },
      { id: 'df3', position: 'DF', x: 0.72, y: 0.7 },
      { id: 'mf1', position: 'MF', x: 0.2, y: 0.48 },
      { id: 'mf2', position: 'MF', x: 0.4, y: 0.5 },
      { id: 'mf3', position: 'MF', x: 0.6, y: 0.5 },
      { id: 'mf4', position: 'MF', x: 0.8, y: 0.48 },
      { id: 'fw1', position: 'FW', x: 0.22, y: 0.18 },
      { id: 'fw2', position: 'FW', x: 0.5, y: 0.13 },
      { id: 'fw3', position: 'FW', x: 0.78, y: 0.18 }
    ]
  }
];

const player = (
  id: string,
  name: string,
  position: Position,
  role: string,
  rating: number,
  rarity: PlayerCardData['rarity'],
  skill: string,
  portrait: string,
  era: PlayerCardData['era'],
  stats: [number, number, number, number],
  color?: number
): PlayerCardData => ({
  id,
  name,
  position,
  role,
  rarity,
  rating,
  attack: stats[0],
  defense: stats[1],
  speed: stats[2],
  stamina: stats[3],
  skill,
  portrait,
  era,
  color: color && rarity === 'legend' ? color : rarityMeta[rarity].color
});

const starterPortraits = [
  portraits.saka,
  portraits.foden,
  portraits.gavi,
  portraits.rice,
  portraits.trent,
  portraits.militao,
  portraits.maignan,
  portraits.son,
  portraits.pedri,
  portraits.davies,
  portraits.osimhen
];

const starterPlayers: PlayerCardData[] = [
  player('st_fw_lin', '林浩', 'FW', '青训前锋', 72, 'silver', '抢点射门', starterPortraits[0], 'current', [75, 38, 76, 72]),
  player('st_fw_chen', '陈锐', 'FW', '速度边锋', 69, 'bronze', '快速前插', starterPortraits[7], 'current', [70, 34, 78, 68]),
  player('st_fw_wu', '吴峻', 'FW', '支点中锋', 74, 'silver', '背身做球', starterPortraits[10], 'current', [76, 46, 66, 76]),
  player('st_mf_luo', '罗一鸣', 'MF', '组织中场', 73, 'silver', '短传节奏', starterPortraits[1], 'current', [70, 64, 70, 76]),
  player('st_mf_zhao', '赵启航', 'MF', '覆盖中场', 70, 'bronze', '积极跑动', starterPortraits[2], 'current', [66, 68, 72, 78]),
  player('st_mf_qin', '秦川', 'MF', '防守后腰', 75, 'silver', '中路拦截', starterPortraits[3], 'current', [62, 76, 66, 80]),
  player('st_df_han', '韩越', 'DF', '边路后卫', 71, 'bronze', '边路回追', starterPortraits[4], 'current', [58, 72, 76, 74]),
  player('st_df_gao', '高远', 'DF', '中卫', 74, 'silver', '头球解围', starterPortraits[5], 'current', [50, 78, 66, 76]),
  player('st_df_xu', '徐磊', 'DF', '盯人中卫', 72, 'silver', '贴身盯防', starterPortraits[9], 'current', [52, 76, 72, 74]),
  player('st_df_shen', '沈杰', 'DF', '防守边卫', 69, 'bronze', '稳健卡位', starterPortraits[4], 'current', [54, 72, 70, 74]),
  player('st_gk_tang', '唐森', 'GK', '年轻门将', 73, 'silver', '反应扑救', starterPortraits[6], 'current', [16, 76, 62, 74]),
  player('st_gk_yu', '余航', 'GK', '替补门将', 67, 'bronze', '单拳击球', starterPortraits[6], 'current', [14, 70, 58, 70]),
  player('st_df_fang', '方奕', 'DF', '中卫', 68, 'bronze', '正面封堵', starterPortraits[5], 'current', [48, 72, 64, 72]),
  player('st_mf_ma', '马骁', 'MF', '前插中场', 68, 'bronze', '后插上', starterPortraits[8], 'current', [68, 60, 70, 70]),
  player('st_fw_jiang', '蒋翼', 'FW', '替补射手', 66, 'bronze', '禁区嗅觉', starterPortraits[0], 'current', [70, 32, 68, 68])
];

type ExtraPlayerSpec = {
  id: string;
  name: string;
  position: Position;
  role: string;
  rating: number;
  rarity: PlayerCardData['rarity'];
  skill: string;
  slug: string;
  stats: [number, number, number, number];
};

const extraPortrait = (slug: string) => `/assets/players/generated/extra/${slug}.png`;

const extraPlayerSpecs: ExtraPlayerSpec[] = [
  { id: 'fw_julian_alvarez', name: '胡利安·阿尔瓦雷斯', position: 'FW', role: '前锋', rating: 90, rarity: 'purple', skill: '灵动前插', slug: 'julian-alvarez', stats: [90, 60, 86, 90] },
  { id: 'fw_rashford', name: '拉什福德', position: 'FW', role: '边锋', rating: 88, rarity: 'gold', skill: '直线爆破', slug: 'rashford', stats: [87, 42, 92, 82] },
  { id: 'fw_sancho', name: '桑乔', position: 'FW', role: '边锋', rating: 86, rarity: 'gold', skill: '细腻盘带', slug: 'sancho', stats: [84, 42, 82, 78] },
  { id: 'fw_anthony_gordon', name: '安东尼·戈登', position: 'FW', role: '边锋', rating: 86, rarity: 'gold', skill: '高速反插', slug: 'anthony-gordon', stats: [84, 50, 90, 86] },
  { id: 'fw_toney', name: '伊万·托尼', position: 'FW', role: '中锋', rating: 86, rarity: 'gold', skill: '点球专家', slug: 'toney', stats: [88, 52, 72, 84] },
  { id: 'fw_watkins', name: '沃特金斯', position: 'FW', role: '中锋', rating: 88, rarity: 'gold', skill: '身后冲刺', slug: 'watkins', stats: [88, 48, 88, 88] },
  { id: 'fw_marcus_thuram', name: '马库斯·图拉姆', position: 'FW', role: '前锋', rating: 87, rarity: 'gold', skill: '强力冲击', slug: 'marcus-thuram', stats: [86, 54, 86, 86] },
  { id: 'fw_kolo_muani', name: '穆阿尼', position: 'FW', role: '前锋', rating: 87, rarity: 'gold', skill: '反击突袭', slug: 'kolo-muani', stats: [86, 46, 91, 82] },
  { id: 'fw_coman', name: '科曼', position: 'FW', role: '边锋', rating: 88, rarity: 'gold', skill: '边路加速', slug: 'coman', stats: [86, 44, 93, 80] },
  { id: 'fw_barcola', name: '巴尔科拉', position: 'FW', role: '边锋', rating: 86, rarity: 'gold', skill: '轻盈变向', slug: 'barcola', stats: [84, 40, 90, 78] },
  { id: 'fw_nkunku', name: '恩昆库', position: 'FW', role: '影锋', rating: 88, rarity: 'gold', skill: '禁区游走', slug: 'nkunku', stats: [88, 52, 84, 80] },
  { id: 'fw_guirassy', name: '吉拉西', position: 'FW', role: '中锋', rating: 87, rarity: 'gold', skill: '强力抢点', slug: 'guirassy', stats: [89, 50, 76, 84] },
  { id: 'fw_jonathan_david', name: '乔纳森·戴维', position: 'FW', role: '前锋', rating: 87, rarity: 'gold', skill: '冷静单刀', slug: 'jonathan-david', stats: [87, 46, 84, 82] },
  { id: 'fw_santiago_gimenez', name: '圣地亚哥·希门尼斯', position: 'FW', role: '中锋', rating: 86, rarity: 'gold', skill: '门前嗅觉', slug: 'santiago-gimenez', stats: [88, 46, 78, 84] },
  { id: 'fw_sesko', name: '谢什科', position: 'FW', role: '中锋', rating: 86, rarity: 'gold', skill: '高点冲击', slug: 'sesko', stats: [87, 48, 84, 84] },
  { id: 'fw_brobbey', name: '布罗贝', position: 'FW', role: '中锋', rating: 84, rarity: 'gold', skill: '背身抗压', slug: 'brobbey', stats: [84, 50, 78, 84] },
  { id: 'fw_memphis', name: '德佩', position: 'FW', role: '前锋', rating: 86, rarity: 'gold', skill: '弧线劲射', slug: 'memphis', stats: [87, 50, 80, 78] },
  { id: 'fw_weghorst', name: '韦霍斯特', position: 'FW', role: '中锋', rating: 82, rarity: 'silver', skill: '高空支点', slug: 'weghorst', stats: [83, 58, 60, 82] },
  { id: 'fw_ferran_torres', name: '费兰·托雷斯', position: 'FW', role: '边锋', rating: 85, rarity: 'gold', skill: '斜线跑位', slug: 'ferran-torres', stats: [85, 50, 84, 82] },
  { id: 'fw_morata', name: '莫拉塔', position: 'FW', role: '中锋', rating: 85, rarity: 'gold', skill: '头球抢点', slug: 'morata', stats: [86, 52, 78, 84] },
  { id: 'fw_oyarzabal', name: '奥亚萨瓦尔', position: 'FW', role: '边锋', rating: 85, rarity: 'gold', skill: '稳健终结', slug: 'oyarzabal', stats: [85, 58, 78, 84] },
  { id: 'fw_gerard_moreno', name: '赫拉德·莫雷诺', position: 'FW', role: '中锋', rating: 85, rarity: 'gold', skill: '左脚终结', slug: 'gerard-moreno', stats: [86, 52, 74, 78] },
  { id: 'fw_ansu_fati', name: '法蒂', position: 'FW', role: '边锋', rating: 82, rarity: 'silver', skill: '禁区闪击', slug: 'ansu-fati', stats: [82, 38, 86, 72] },
  { id: 'fw_bryan_zaragoza', name: '布赖恩·萨拉戈萨', position: 'FW', role: '边锋', rating: 81, rarity: 'silver', skill: '小范围突破', slug: 'bryan-zaragoza', stats: [80, 42, 86, 76] },
  { id: 'fw_yeremy_pino', name: '耶雷米·皮诺', position: 'FW', role: '边锋', rating: 82, rarity: 'silver', skill: '边路穿插', slug: 'yeremy-pino', stats: [81, 48, 84, 78] },
  { id: 'fw_goncalo_ramos', name: '贡萨洛·拉莫斯', position: 'FW', role: '中锋', rating: 86, rarity: 'gold', skill: '禁区杀手', slug: 'goncalo-ramos', stats: [87, 48, 78, 82] },
  { id: 'fw_joao_felix', name: '若昂·菲利克斯', position: 'FW', role: '影锋', rating: 87, rarity: 'gold', skill: '灵感挑传', slug: 'joao-felix', stats: [87, 46, 82, 76] },
  { id: 'fw_pedro_neto', name: '佩德罗·内托', position: 'FW', role: '边锋', rating: 85, rarity: 'gold', skill: '高速传中', slug: 'pedro-neto', stats: [84, 46, 90, 78] },
  { id: 'fw_francisco_conceicao', name: '弗朗西斯科·孔塞桑', position: 'FW', role: '边锋', rating: 82, rarity: 'silver', skill: '连续变向', slug: 'francisco-conceicao', stats: [82, 42, 86, 78] },
  { id: 'fw_diogo_jota', name: '若塔', position: 'FW', role: '前锋', rating: 87, rarity: 'gold', skill: '门前补射', slug: 'diogo-jota', stats: [88, 52, 82, 82] },
  { id: 'fw_gabriel_jesus', name: '热苏斯', position: 'FW', role: '前锋', rating: 86, rarity: 'gold', skill: '压迫跑位', slug: 'gabriel-jesus', stats: [86, 56, 84, 84] },
  { id: 'fw_richarlison', name: '理查利森', position: 'FW', role: '中锋', rating: 85, rarity: 'gold', skill: '强硬冲顶', slug: 'richarlison', stats: [86, 56, 80, 84] },
  { id: 'fw_endrick', name: '恩德里克', position: 'FW', role: '前锋', rating: 84, rarity: 'gold', skill: '少年爆发', slug: 'endrick', stats: [84, 44, 88, 78] },
  { id: 'fw_rodrygo', name: '罗德里戈', position: 'FW', role: '边锋', rating: 89, rarity: 'gold', skill: '灵巧终结', slug: 'rodrygo', stats: [88, 48, 88, 82] },
  { id: 'fw_martinelli', name: '马丁内利', position: 'FW', role: '边锋', rating: 87, rarity: 'gold', skill: '边路冲刺', slug: 'martinelli', stats: [86, 50, 91, 84] },
  { id: 'fw_evanilson', name: '埃万尼尔森', position: 'FW', role: '中锋', rating: 82, rarity: 'silver', skill: '前点抢射', slug: 'evanilson', stats: [83, 46, 78, 80] },
  { id: 'fw_taremi', name: '塔雷米', position: 'FW', role: '中锋', rating: 84, rarity: 'gold', skill: '禁区冷静', slug: 'taremi', stats: [85, 54, 74, 82] },
  { id: 'fw_azmoun', name: '阿兹蒙', position: 'FW', role: '中锋', rating: 82, rarity: 'silver', skill: '灵活抢点', slug: 'azmoun', stats: [82, 50, 78, 80] },
  { id: 'fw_hwang_hee_chan', name: '黄喜灿', position: 'FW', role: '前锋', rating: 84, rarity: 'gold', skill: '反击冲刺', slug: 'hwang-hee-chan', stats: [84, 52, 86, 84] },
  { id: 'fw_cho_gue_sung', name: '曹圭成', position: 'FW', role: '中锋', rating: 80, rarity: 'silver', skill: '头球争顶', slug: 'cho-gue-sung', stats: [81, 50, 72, 80] },
  { id: 'fw_furuhashi', name: '古桥亨梧', position: 'FW', role: '前锋', rating: 82, rarity: 'silver', skill: '身后偷袭', slug: 'furuhashi', stats: [83, 42, 84, 78] },
  { id: 'fw_minamino', name: '南野拓实', position: 'FW', role: '前锋', rating: 83, rarity: 'silver', skill: '门前灵感', slug: 'minamino', stats: [83, 50, 80, 78] },
  { id: 'fw_berardi', name: '贝拉尔迪', position: 'FW', role: '右锋', rating: 84, rarity: 'gold', skill: '左脚抽射', slug: 'berardi', stats: [85, 52, 76, 80] },
  { id: 'fw_scamacca', name: '斯卡马卡', position: 'FW', role: '中锋', rating: 84, rarity: 'gold', skill: '重炮远射', slug: 'scamacca', stats: [86, 52, 72, 82] },
  { id: 'fw_retegui', name: '雷特吉', position: 'FW', role: '中锋', rating: 83, rarity: 'silver', skill: '正面抢点', slug: 'retegui', stats: [84, 48, 76, 82] },
  { id: 'fw_dybala', name: '迪巴拉', position: 'FW', role: '影锋', rating: 88, rarity: 'gold', skill: '左脚灵感', slug: 'dybala', stats: [89, 46, 80, 76] },
  { id: 'fw_angel_correa', name: '安赫尔·科雷亚', position: 'FW', role: '影锋', rating: 83, rarity: 'silver', skill: '禁区搅动', slug: 'angel-correa', stats: [83, 54, 80, 82] },
  { id: 'fw_nicolas_gonzalez', name: '尼科拉斯·冈萨雷斯', position: 'FW', role: '边锋', rating: 84, rarity: 'gold', skill: '后点包抄', slug: 'nicolas-gonzalez', stats: [84, 58, 84, 84] },
  { id: 'fw_balogun', name: '巴洛贡', position: 'FW', role: '中锋', rating: 82, rarity: 'silver', skill: '单刀突进', slug: 'balogun', stats: [83, 42, 84, 78] },
  { id: 'fw_pepi', name: '佩皮', position: 'FW', role: '中锋', rating: 80, rarity: 'silver', skill: '门前抢点', slug: 'pepi', stats: [81, 44, 76, 78] },
  { id: 'fw_tim_weah', name: '蒂莫西·维阿', position: 'FW', role: '边锋', rating: 81, rarity: 'silver', skill: '边路前插', slug: 'tim-weah', stats: [80, 56, 86, 80] },
  { id: 'fw_zirkzee', name: '齐尔克泽', position: 'FW', role: '中锋', rating: 83, rarity: 'silver', skill: '支点分球', slug: 'zirkzee', stats: [83, 52, 76, 80] },
  { id: 'fw_hojlund', name: '霍伊伦', position: 'FW', role: '中锋', rating: 84, rarity: 'gold', skill: '强突射门', slug: 'hojlund', stats: [84, 46, 88, 82] },
  { id: 'fw_gyokeres', name: '约克雷斯', position: 'FW', role: '中锋', rating: 89, rarity: 'gold', skill: '强力奔袭', slug: 'gyokeres', stats: [90, 52, 86, 90] },
  { id: 'fw_wu_lei', name: '武磊', position: 'FW', role: '前锋', rating: 78, rarity: 'silver', skill: '机敏前插', slug: 'wu-lei', stats: [80, 42, 82, 78] },
  { id: 'fw_zhang_yuning', name: '张玉宁', position: 'FW', role: '中锋', rating: 75, rarity: 'silver', skill: '背身做球', slug: 'zhang-yuning', stats: [76, 50, 68, 78] },
  { id: 'fw_alan_carvalho', name: '阿兰', position: 'FW', role: '前锋', rating: 76, rarity: 'silver', skill: '门前终结', slug: 'alan-carvalho', stats: [78, 44, 74, 76] },
  { id: 'fw_fernandinho_china', name: '费南多', position: 'FW', role: '边锋', rating: 76, rarity: 'silver', skill: '边路加速', slug: 'fernandinho-china', stats: [76, 42, 82, 74] },
  { id: 'fw_wei_shihao', name: '韦世豪', position: 'FW', role: '边锋', rating: 75, rarity: 'silver', skill: '内切兜射', slug: 'wei-shihao', stats: [76, 46, 78, 76] },
  { id: 'fw_lin_liangming', name: '林良铭', position: 'FW', role: '边锋', rating: 73, rarity: 'silver', skill: '边路穿插', slug: 'lin-liangming', stats: [74, 44, 78, 74] },

  { id: 'mf_cole_palmer', name: '科尔·帕尔默', position: 'MF', role: '前腰', rating: 90, rarity: 'purple', skill: '冷静创造', slug: 'cole-palmer', stats: [90, 58, 82, 86] },
  { id: 'mf_mount', name: '芒特', position: 'MF', role: '前腰', rating: 84, rarity: 'gold', skill: '前场压迫', slug: 'mount', stats: [82, 66, 78, 84] },
  { id: 'mf_maddison', name: '麦迪逊', position: 'MF', role: '前腰', rating: 86, rarity: 'gold', skill: '定位球传送', slug: 'maddison', stats: [86, 58, 76, 82] },
  { id: 'mf_eze', name: '埃泽', position: 'MF', role: '前腰', rating: 86, rarity: 'gold', skill: '灵巧摆脱', slug: 'eze', stats: [86, 52, 84, 82] },
  { id: 'mf_gallagher', name: '加拉格尔', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '高压逼抢', slug: 'gallagher', stats: [80, 78, 78, 90] },
  { id: 'mf_mainoo', name: '梅努', position: 'MF', role: '中场', rating: 83, rarity: 'silver', skill: '稳健推进', slug: 'mainoo', stats: [78, 76, 76, 82] },
  { id: 'mf_phillips', name: '菲利普斯', position: 'MF', role: '后腰', rating: 80, rarity: 'silver', skill: '中场扫荡', slug: 'phillips', stats: [72, 78, 70, 82] },
  { id: 'mf_kante', name: '坎特', position: 'MF', role: '后腰', rating: 88, rarity: 'gold', skill: '全场拦截', slug: 'kante', stats: [74, 90, 78, 90] },
  { id: 'mf_rabiot', name: '拉比奥', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '左路覆盖', slug: 'rabiot', stats: [80, 82, 76, 88] },
  { id: 'mf_zaire_emery', name: '扎伊尔-埃梅里', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '少年推进', slug: 'zaire-emery', stats: [80, 80, 80, 86] },
  { id: 'mf_vitinha', name: '维蒂尼亚', position: 'MF', role: '中场', rating: 88, rarity: 'gold', skill: '短传节奏', slug: 'vitinha', stats: [84, 76, 78, 86] },
  { id: 'mf_joao_neves', name: '若昂·内维斯', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '敏捷拦截', slug: 'joao-neves', stats: [80, 82, 80, 88] },
  { id: 'mf_ruben_neves', name: '鲁本·内维斯', position: 'MF', role: '后腰', rating: 85, rarity: 'gold', skill: '长传转移', slug: 'ruben-neves', stats: [80, 80, 70, 84] },
  { id: 'mf_matheus_nunes', name: '马特乌斯·努内斯', position: 'MF', role: '中场', rating: 83, rarity: 'silver', skill: '带球推进', slug: 'matheus-nunes', stats: [78, 76, 82, 82] },
  { id: 'mf_gravenberch', name: '赫拉芬贝赫', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '纵向推进', slug: 'gravenberch', stats: [80, 78, 80, 84] },
  { id: 'mf_xavi_simons', name: '哈维·西蒙斯', position: 'MF', role: '前腰', rating: 87, rarity: 'gold', skill: '灵感直塞', slug: 'xavi-simons', stats: [86, 58, 84, 82] },
  { id: 'mf_reijnders', name: '赖因德斯', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '节奏推进', slug: 'reijnders', stats: [82, 76, 78, 86] },
  { id: 'mf_koopmeiners', name: '库普梅纳斯', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '远射调度', slug: 'koopmeiners', stats: [84, 78, 72, 86] },
  { id: 'mf_frenkie_de_jong', name: '弗朗基·德容', position: 'MF', role: '中场', rating: 89, rarity: 'gold', skill: '摆脱推进', slug: 'frenkie-de-jong', stats: [84, 80, 80, 86] },
  { id: 'mf_de_roon', name: '德容恩', position: 'MF', role: '后腰', rating: 82, rarity: 'silver', skill: '防守卡位', slug: 'de-roon', stats: [72, 82, 70, 86] },
  { id: 'mf_zubimendi', name: '苏比门迪', position: 'MF', role: '后腰', rating: 86, rarity: 'gold', skill: '中路调度', slug: 'zubimendi', stats: [78, 84, 72, 86] },
  { id: 'mf_merino', name: '梅里诺', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '空中对抗', slug: 'merino', stats: [82, 82, 72, 88] },
  { id: 'mf_fabian_ruiz', name: '法比安·鲁伊斯', position: 'MF', role: '中场', rating: 87, rarity: 'gold', skill: '左脚调度', slug: 'fabian-ruiz', stats: [84, 78, 72, 84] },
  { id: 'mf_dani_olmo', name: '奥尔莫', position: 'MF', role: '前腰', rating: 88, rarity: 'gold', skill: '肋部穿插', slug: 'dani-olmo', stats: [87, 62, 82, 82] },
  { id: 'mf_arda_guler', name: '居莱尔', position: 'MF', role: '前腰', rating: 84, rarity: 'gold', skill: '左脚灵气', slug: 'arda-guler', stats: [84, 50, 80, 76] },
  { id: 'mf_calhanoglu', name: '恰尔汗奥卢', position: 'MF', role: '后腰', rating: 88, rarity: 'gold', skill: '定位球大师', slug: 'calhanoglu', stats: [86, 80, 70, 84] },
  { id: 'mf_koke', name: '科克', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '稳健分球', slug: 'koke', stats: [78, 82, 68, 84] },
  { id: 'mf_llorente', name: '马科斯·略伦特', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '高速前插', slug: 'llorente', stats: [82, 80, 88, 88] },
  { id: 'mf_szoboszlai', name: '索博斯洛伊', position: 'MF', role: '前腰', rating: 87, rarity: 'gold', skill: '重炮远射', slug: 'szoboszlai', stats: [86, 68, 82, 86] },
  { id: 'mf_mctominay', name: '麦克托米奈', position: 'MF', role: '中场', rating: 83, rarity: 'silver', skill: '后点冲击', slug: 'mctominay', stats: [80, 80, 72, 86] },
  { id: 'mf_gilmour', name: '吉尔摩', position: 'MF', role: '中场', rating: 80, rarity: 'silver', skill: '短传梳理', slug: 'gilmour', stats: [76, 72, 74, 80] },
  { id: 'mf_eriksen', name: '埃里克森', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '精准直塞', slug: 'eriksen', stats: [84, 66, 66, 78] },
  { id: 'mf_hojbjerg', name: '霍伊别尔', position: 'MF', role: '后腰', rating: 83, rarity: 'silver', skill: '强硬拦截', slug: 'hojbjerg', stats: [76, 82, 70, 84] },
  { id: 'mf_amrabat', name: '阿姆拉巴特', position: 'MF', role: '后腰', rating: 82, rarity: 'silver', skill: '中场缠斗', slug: 'amrabat', stats: [74, 82, 72, 86] },
  { id: 'mf_ziyech', name: '齐耶赫', position: 'MF', role: '前腰', rating: 84, rarity: 'gold', skill: '左脚传中', slug: 'ziyech', stats: [85, 54, 74, 78] },
  { id: 'mf_onana', name: '阿马杜·奥纳纳', position: 'MF', role: '后腰', rating: 84, rarity: 'gold', skill: '高大屏障', slug: 'amadou-onana', stats: [74, 86, 76, 86] },
  { id: 'mf_partey', name: '托马斯·帕尔特伊', position: 'MF', role: '后腰', rating: 84, rarity: 'gold', skill: '中路屏障', slug: 'partey', stats: [78, 84, 72, 82] },
  { id: 'mf_kudus', name: '库杜斯', position: 'MF', role: '前腰', rating: 86, rarity: 'gold', skill: '强突摆脱', slug: 'kudus', stats: [86, 58, 86, 84] },
  { id: 'mf_caicedo', name: '凯塞多', position: 'MF', role: '后腰', rating: 86, rarity: 'gold', skill: '覆盖拦截', slug: 'caicedo', stats: [76, 86, 80, 88] },
  { id: 'mf_paqueta', name: '帕奎塔', position: 'MF', role: '前腰', rating: 86, rarity: 'gold', skill: '桑巴传控', slug: 'paqueta', stats: [86, 70, 78, 84] },
  { id: 'mf_bruno_guimaraes', name: '吉马良斯', position: 'MF', role: '中场', rating: 88, rarity: 'gold', skill: '攻防转换', slug: 'bruno-guimaraes', stats: [84, 82, 76, 88] },
  { id: 'mf_casemiro', name: '卡塞米罗', position: 'MF', role: '后腰', rating: 87, rarity: 'gold', skill: '硬朗拦截', slug: 'casemiro', stats: [76, 88, 68, 84] },
  { id: 'mf_douglas_luiz', name: '道格拉斯·路易斯', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '长短调度', slug: 'douglas-luiz', stats: [82, 78, 74, 86] },
  { id: 'mf_joelinton', name: '若埃林通', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '强硬推进', slug: 'joelinton', stats: [82, 80, 76, 88] },
  { id: 'mf_paredes', name: '帕雷德斯', position: 'MF', role: '后腰', rating: 83, rarity: 'silver', skill: '长传分边', slug: 'paredes', stats: [78, 80, 68, 82] },
  { id: 'mf_de_paul', name: '德保罗', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '全场奔袭', slug: 'de-paul', stats: [82, 80, 80, 90] },
  { id: 'mf_palacios', name: '帕拉西奥斯', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '节奏梳理', slug: 'palacios', stats: [80, 78, 76, 84] },
  { id: 'mf_lo_celso', name: '洛塞尔索', position: 'MF', role: '前腰', rating: 83, rarity: 'silver', skill: '左脚直塞', slug: 'lo-celso', stats: [83, 66, 74, 80] },
  { id: 'mf_almada', name: '阿尔马达', position: 'MF', role: '前腰', rating: 82, rarity: 'silver', skill: '灵动组织', slug: 'almada', stats: [82, 54, 82, 78] },
  { id: 'mf_arrascaeta', name: '德阿拉斯凯塔', position: 'MF', role: '前腰', rating: 84, rarity: 'gold', skill: '禁区传球', slug: 'arrascaeta', stats: [84, 58, 76, 80] },
  { id: 'mf_bentancur', name: '本坦库尔', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '中路推进', slug: 'bentancur', stats: [80, 80, 76, 84] },
  { id: 'mf_ugarte', name: '乌加特', position: 'MF', role: '后腰', rating: 85, rarity: 'gold', skill: '凶狠抢断', slug: 'ugarte', stats: [74, 86, 78, 88] },
  { id: 'mf_kessie', name: '凯西', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '力量覆盖', slug: 'kessie', stats: [80, 82, 76, 86] },
  { id: 'mf_bennacer', name: '本纳塞尔', position: 'MF', role: '中场', rating: 84, rarity: 'gold', skill: '小范围摆脱', slug: 'bennacer', stats: [80, 80, 78, 84] },
  { id: 'mf_zielinski', name: '泽林斯基', position: 'MF', role: '中场', rating: 85, rarity: 'gold', skill: '穿针引线', slug: 'zielinski', stats: [84, 72, 76, 82] },
  { id: 'mf_milinkovic_savic', name: '米林科维奇', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '高点组织', slug: 'milinkovic-savic', stats: [84, 82, 72, 86] },
  { id: 'mf_samardzic', name: '萨马尔季奇', position: 'MF', role: '前腰', rating: 81, rarity: 'silver', skill: '左脚妙传', slug: 'samardzic', stats: [81, 58, 74, 78] },
  { id: 'mf_brozovic', name: '布罗佐维奇', position: 'MF', role: '后腰', rating: 85, rarity: 'gold', skill: '节拍控制', slug: 'brozovic', stats: [80, 82, 70, 86] },
  { id: 'mf_kovacic', name: '科瓦契奇', position: 'MF', role: '中场', rating: 86, rarity: 'gold', skill: '盘带出球', slug: 'kovacic', stats: [82, 78, 80, 84] },
  { id: 'mf_majer', name: '马耶尔', position: 'MF', role: '前腰', rating: 82, rarity: 'silver', skill: '左脚组织', slug: 'majer', stats: [82, 62, 74, 80] },
  { id: 'mf_sucic', name: '苏契奇', position: 'MF', role: '中场', rating: 80, rarity: 'silver', skill: '青年推进', slug: 'sucic', stats: [78, 74, 76, 80] },
  { id: 'mf_zhang_xizhe', name: '张稀哲', position: 'MF', role: '前腰', rating: 73, rarity: 'silver', skill: '直塞组织', slug: 'zhang-xizhe', stats: [74, 58, 68, 74] },
  { id: 'mf_wu_xi', name: '吴曦', position: 'MF', role: '中场', rating: 74, rarity: 'silver', skill: '后插上', slug: 'wu-xi', stats: [72, 70, 68, 76] },
  { id: 'mf_wang_shangyuan', name: '王上源', position: 'MF', role: '后腰', rating: 72, rarity: 'silver', skill: '中场卡位', slug: 'wang-shangyuan', stats: [66, 72, 66, 76] },
  { id: 'mf_xu_xin', name: '徐新', position: 'MF', role: '中场', rating: 72, rarity: 'silver', skill: '节奏分球', slug: 'xu-xin', stats: [68, 68, 68, 74] },
  { id: 'mf_dai_wai_tsun', name: '戴伟浚', position: 'MF', role: '中场', rating: 73, rarity: 'silver', skill: '带球推进', slug: 'dai-wai-tsun', stats: [72, 62, 74, 74] },
  { id: 'mf_li_yuanyi', name: '李源一', position: 'MF', role: '中场', rating: 72, rarity: 'silver', skill: '积极跑动', slug: 'li-yuanyi', stats: [68, 68, 70, 76] },
  { id: 'mf_xie_pengfei', name: '谢鹏飞', position: 'MF', role: '边前卫', rating: 73, rarity: 'silver', skill: '边路传中', slug: 'xie-pengfei', stats: [72, 58, 72, 74] },
  { id: 'mf_gao_tianyi', name: '高天意', position: 'MF', role: '中场', rating: 71, rarity: 'bronze', skill: '前插接应', slug: 'gao-tianyi', stats: [68, 66, 70, 74] },
  { id: 'mf_cheng_jin', name: '程进', position: 'MF', role: '前腰', rating: 72, rarity: 'silver', skill: '中路串联', slug: 'cheng-jin', stats: [72, 60, 70, 72] },

  { id: 'df_stones', name: '斯通斯', position: 'DF', role: '中卫', rating: 88, rarity: 'gold', skill: '出球中卫', slug: 'stones', stats: [64, 88, 74, 86] },
  { id: 'df_walker', name: '沃克', position: 'DF', role: '右卫', rating: 87, rarity: 'gold', skill: '极速回追', slug: 'walker', stats: [68, 86, 92, 84] },
  { id: 'df_luke_shaw', name: '卢克·肖', position: 'DF', role: '左卫', rating: 83, rarity: 'silver', skill: '边路支援', slug: 'luke-shaw', stats: [72, 82, 78, 80] },
  { id: 'df_maguire', name: '马奎尔', position: 'DF', role: '中卫', rating: 82, rarity: 'silver', skill: '高空解围', slug: 'maguire', stats: [56, 84, 58, 82] },
  { id: 'df_guehi', name: '格伊', position: 'DF', role: '中卫', rating: 84, rarity: 'gold', skill: '冷静盯防', slug: 'guehi', stats: [52, 84, 78, 82] },
  { id: 'df_reece_james', name: '里斯·詹姆斯', position: 'DF', role: '右卫', rating: 85, rarity: 'gold', skill: '强力传中', slug: 'reece-james', stats: [78, 82, 82, 78] },
  { id: 'df_ben_white', name: '本·怀特', position: 'DF', role: '后卫', rating: 84, rarity: 'gold', skill: '稳健协防', slug: 'ben-white', stats: [68, 84, 78, 84] },
  { id: 'df_trippier', name: '特里皮尔', position: 'DF', role: '右卫', rating: 84, rarity: 'gold', skill: '定位球传中', slug: 'trippier', stats: [76, 82, 72, 82] },
  { id: 'df_udogie', name: '乌多吉', position: 'DF', role: '左卫', rating: 83, rarity: 'silver', skill: '边路推进', slug: 'udogie', stats: [72, 80, 84, 84] },
  { id: 'df_dimarco', name: '迪马尔科', position: 'DF', role: '左卫', rating: 86, rarity: 'gold', skill: '精准传中', slug: 'dimarco', stats: [80, 82, 80, 84] },
  { id: 'df_acerbi', name: '阿切尔比', position: 'DF', role: '中卫', rating: 84, rarity: 'gold', skill: '老练站位', slug: 'acerbi', stats: [52, 86, 60, 82] },
  { id: 'df_darmian', name: '达米安', position: 'DF', role: '后卫', rating: 83, rarity: 'silver', skill: '多面防守', slug: 'darmian', stats: [64, 84, 72, 82] },
  { id: 'df_di_lorenzo', name: '迪洛伦佐', position: 'DF', role: '右卫', rating: 84, rarity: 'gold', skill: '边路稳定', slug: 'di-lorenzo', stats: [72, 84, 78, 84] },
  { id: 'df_bastoni', name: '巴斯托尼', position: 'DF', role: '中卫', rating: 88, rarity: 'gold', skill: '左脚出球', slug: 'bastoni', stats: [60, 90, 74, 86] },
  { id: 'df_scalvini', name: '斯卡尔维尼', position: 'DF', role: '中卫', rating: 83, rarity: 'silver', skill: '青年卡位', slug: 'scalvini', stats: [52, 84, 72, 82] },
  { id: 'df_pavard', name: '帕瓦尔', position: 'DF', role: '后卫', rating: 86, rarity: 'gold', skill: '稳健补位', slug: 'pavard', stats: [66, 86, 72, 84] },
  { id: 'df_lucas_hernandez', name: '卢卡斯·埃尔南德斯', position: 'DF', role: '中卫', rating: 86, rarity: 'gold', skill: '强硬对抗', slug: 'lucas-hernandez', stats: [62, 86, 78, 82] },
  { id: 'df_konate', name: '科纳特', position: 'DF', role: '中卫', rating: 86, rarity: 'gold', skill: '身体压制', slug: 'konate', stats: [54, 88, 78, 84] },
  { id: 'df_varane', name: '瓦拉内', position: 'DF', role: '中卫', rating: 85, rarity: 'gold', skill: '冷静回追', slug: 'varane', stats: [52, 86, 76, 80] },
  { id: 'df_laporte', name: '拉波尔特', position: 'DF', role: '中卫', rating: 86, rarity: 'gold', skill: '左脚长传', slug: 'laporte', stats: [58, 88, 68, 84] },
  { id: 'df_carvajal', name: '卡瓦哈尔', position: 'DF', role: '右卫', rating: 87, rarity: 'gold', skill: '边路铁闸', slug: 'carvajal', stats: [76, 86, 82, 86] },
  { id: 'df_nacho', name: '纳乔', position: 'DF', role: '后卫', rating: 83, rarity: 'silver', skill: '可靠替补', slug: 'nacho', stats: [60, 84, 74, 82] },
  { id: 'df_grimaldo', name: '格里马尔多', position: 'DF', role: '左卫', rating: 86, rarity: 'gold', skill: '左路传送', slug: 'grimaldo', stats: [82, 80, 82, 84] },
  { id: 'df_cucurella', name: '库库雷利亚', position: 'DF', role: '左卫', rating: 83, rarity: 'silver', skill: '贴身逼抢', slug: 'cucurella', stats: [70, 82, 80, 84] },
  { id: 'df_araujo', name: '阿劳霍', position: 'DF', role: '中卫', rating: 89, rarity: 'gold', skill: '速度中卫', slug: 'araujo', stats: [58, 91, 82, 86] },
  { id: 'df_jose_gimenez', name: '何塞·希门尼斯', position: 'DF', role: '中卫', rating: 85, rarity: 'gold', skill: '强硬头球', slug: 'jose-gimenez', stats: [54, 87, 70, 84] },
  { id: 'df_lisandro_martinez', name: '利桑德罗·马丁内斯', position: 'DF', role: '中卫', rating: 86, rarity: 'gold', skill: '凶狠上抢', slug: 'lisandro-martinez', stats: [58, 87, 74, 82] },
  { id: 'df_cristian_romero', name: '罗梅罗', position: 'DF', role: '中卫', rating: 87, rarity: 'gold', skill: '强势盯防', slug: 'cristian-romero', stats: [58, 89, 76, 86] },
  { id: 'df_otamendi', name: '奥塔门迪', position: 'DF', role: '中卫', rating: 83, rarity: 'silver', skill: '老练对抗', slug: 'otamendi', stats: [54, 85, 62, 82] },
  { id: 'df_molina', name: '莫利纳', position: 'DF', role: '右卫', rating: 84, rarity: 'gold', skill: '套边助攻', slug: 'molina', stats: [72, 82, 82, 84] },
  { id: 'df_acuna', name: '阿库尼亚', position: 'DF', role: '左卫', rating: 84, rarity: 'gold', skill: '强硬传中', slug: 'acuna', stats: [74, 82, 78, 82] },
  { id: 'df_marquinhos', name: '马尔基尼奥斯', position: 'DF', role: '中卫', rating: 88, rarity: 'gold', skill: '防线指挥', slug: 'marquinhos', stats: [58, 90, 76, 86] },
  { id: 'df_gabriel_magalhaes', name: '加布里埃尔', position: 'DF', role: '中卫', rating: 87, rarity: 'gold', skill: '强力制空', slug: 'gabriel-magalhaes', stats: [56, 89, 74, 86] },
  { id: 'df_bremer', name: '布雷默', position: 'DF', role: '中卫', rating: 86, rarity: 'gold', skill: '正面封锁', slug: 'bremer', stats: [54, 88, 74, 86] },
  { id: 'df_danilo', name: '达尼洛', position: 'DF', role: '后卫', rating: 84, rarity: 'gold', skill: '稳健补防', slug: 'danilo', stats: [66, 84, 72, 84] },
  { id: 'df_nuno_mendes', name: '努诺·门德斯', position: 'DF', role: '左卫', rating: 86, rarity: 'gold', skill: '高速套边', slug: 'nuno-mendes', stats: [76, 84, 90, 82] },
  { id: 'df_guerreiro', name: '格雷罗', position: 'DF', role: '左卫', rating: 84, rarity: 'gold', skill: '内收组织', slug: 'guerreiro', stats: [78, 78, 78, 82] },
  { id: 'df_de_ligt', name: '德利赫特', position: 'DF', role: '中卫', rating: 87, rarity: 'gold', skill: '高点防守', slug: 'de-ligt', stats: [56, 89, 70, 84] },
  { id: 'df_dumfries', name: '邓弗里斯', position: 'DF', role: '右卫', rating: 84, rarity: 'gold', skill: '后点冲击', slug: 'dumfries', stats: [76, 82, 84, 86] },
  { id: 'df_botman', name: '博特曼', position: 'DF', role: '中卫', rating: 84, rarity: 'gold', skill: '稳固站位', slug: 'botman', stats: [50, 86, 66, 82] },
  { id: 'df_timber', name: '廷贝尔', position: 'DF', role: '后卫', rating: 84, rarity: 'gold', skill: '灵活出球', slug: 'timber', stats: [66, 84, 80, 82] },
  { id: 'df_jiang_guangtai', name: '蒋光太', position: 'DF', role: '中卫', rating: 75, rarity: 'silver', skill: '正面封堵', slug: 'jiang-guangtai', stats: [48, 78, 68, 76] },
  { id: 'df_zhu_chenjie', name: '朱辰杰', position: 'DF', role: '中卫', rating: 73, rarity: 'silver', skill: '年轻盯防', slug: 'zhu-chenjie', stats: [46, 75, 70, 74] },
  { id: 'df_zhang_linpeng', name: '张琳芃', position: 'DF', role: '后卫', rating: 73, rarity: 'silver', skill: '强硬卡位', slug: 'zhang-linpeng', stats: [58, 74, 68, 74] },
  { id: 'df_gao_zhunyi', name: '高准翼', position: 'DF', role: '后卫', rating: 72, rarity: 'silver', skill: '边中切换', slug: 'gao-zhunyi', stats: [60, 72, 72, 74] },
  { id: 'df_liu_yang', name: '刘洋', position: 'DF', role: '左卫', rating: 72, rarity: 'silver', skill: '左路助攻', slug: 'liu-yang', stats: [64, 70, 74, 74] },
  { id: 'df_wang_shenchao', name: '王燊超', position: 'DF', role: '边卫', rating: 72, rarity: 'silver', skill: '稳健回追', slug: 'wang-shenchao', stats: [62, 72, 70, 74] },
  { id: 'df_li_lei', name: '李磊', position: 'DF', role: '左卫', rating: 71, rarity: 'bronze', skill: '边路传中', slug: 'li-lei', stats: [62, 70, 70, 72] },
  { id: 'df_han_pengfei', name: '韩鹏飞', position: 'DF', role: '中卫', rating: 70, rarity: 'bronze', skill: '高球解围', slug: 'han-pengfei', stats: [44, 72, 64, 72] },
  { id: 'df_hu_hetao', name: '胡荷韬', position: 'DF', role: '边卫', rating: 69, rarity: 'bronze', skill: '年轻冲刺', slug: 'hu-hetao', stats: [58, 68, 74, 72] },

  { id: 'gk_pickford', name: '皮克福德', position: 'GK', role: '门将', rating: 86, rarity: 'gold', skill: '反应扑救', slug: 'pickford', stats: [22, 88, 66, 82] },
  { id: 'gk_ramsdale', name: '拉姆斯代尔', position: 'GK', role: '门将', rating: 83, rarity: 'silver', skill: '快速出击', slug: 'ramsdale', stats: [20, 84, 66, 80] },
  { id: 'gk_david_raya', name: '大卫·拉亚', position: 'GK', role: '门将', rating: 86, rarity: 'gold', skill: '脚下出球', slug: 'david-raya', stats: [24, 87, 68, 82] },
  { id: 'gk_samba', name: '桑巴', position: 'GK', role: '门将', rating: 84, rarity: 'gold', skill: '高大封堵', slug: 'samba', stats: [18, 86, 62, 82] },
  { id: 'gk_vicario', name: '维卡里奥', position: 'GK', role: '门将', rating: 86, rarity: 'gold', skill: '快速下地', slug: 'vicario', stats: [20, 88, 66, 82] },
  { id: 'gk_sommer', name: '索默', position: 'GK', role: '门将', rating: 87, rarity: 'gold', skill: '近距离神扑', slug: 'sommer', stats: [20, 89, 64, 82] },
  { id: 'gk_kobel', name: '科贝尔', position: 'GK', role: '门将', rating: 87, rarity: 'gold', skill: '高球摘取', slug: 'kobel', stats: [20, 89, 66, 84] },
  { id: 'gk_szczesny', name: '什琴斯尼', position: 'GK', role: '门将', rating: 86, rarity: 'gold', skill: '稳定封堵', slug: 'szczesny', stats: [20, 88, 62, 82] },
  { id: 'gk_ter_stegen', name: '特尔施特根', position: 'GK', role: '门将', rating: 90, rarity: 'purple', skill: '门线反应', slug: 'ter-stegen', stats: [24, 92, 68, 84] },
  { id: 'gk_oblak', name: '奥布拉克', position: 'GK', role: '门将', rating: 90, rarity: 'purple', skill: '稳如磐石', slug: 'oblak', stats: [18, 93, 60, 84] },
  { id: 'gk_trubin', name: '特鲁宾', position: 'GK', role: '门将', rating: 84, rarity: 'gold', skill: '高大门线', slug: 'trubin', stats: [18, 86, 62, 82] },
  { id: 'gk_lunin', name: '卢宁', position: 'GK', role: '门将', rating: 85, rarity: 'gold', skill: '冷静扑救', slug: 'lunin', stats: [20, 87, 64, 82] },
  { id: 'gk_bono', name: '布努', position: 'GK', role: '门将', rating: 87, rarity: 'gold', skill: '点球判断', slug: 'bono', stats: [18, 89, 64, 84] },
  { id: 'gk_livakovic', name: '利瓦科维奇', position: 'GK', role: '门将', rating: 84, rarity: 'gold', skill: '淘汰赛扑救', slug: 'livakovic', stats: [18, 86, 64, 82] },
  { id: 'gk_yan_junling', name: '颜骏凌', position: 'GK', role: '门将', rating: 73, rarity: 'silver', skill: '门线扑救', slug: 'yan-junling', stats: [16, 76, 60, 74] },
  { id: 'gk_wang_dalei', name: '王大雷', position: 'GK', role: '门将', rating: 73, rarity: 'silver', skill: '激情出击', slug: 'wang-dalei', stats: [18, 75, 62, 74] },
  { id: 'gk_liu_dianzuo', name: '刘殿座', position: 'GK', role: '门将', rating: 71, rarity: 'bronze', skill: '稳健站位', slug: 'liu-dianzuo', stats: [16, 73, 60, 72] }
];

const extraPlayers = extraPlayerSpecs.map((spec) =>
  player(spec.id, spec.name, spec.position, spec.role, spec.rating, spec.rarity, spec.skill, extraPortrait(spec.slug), 'current', spec.stats)
);

const extraPlayerIds = extraPlayers.map((player) => player.id);

export const players: PlayerCardData[] = [
  ...starterPlayers,
  player('fw_mbappe', '姆巴佩', 'FW', '前锋', 96, 'legend', '极速冲刺', portraits.mbappe, 'current', [96, 42, 98, 86], 0xffc43b),
  player('fw_haaland', '哈兰德', 'FW', '中锋', 95, 'legend', '禁区终结', portraits.haaland, 'current', [98, 48, 88, 90], 0xffc43b),
  player('fw_messi', '梅西', 'FW', '右锋', 95, 'legend', '灵感盘带', portraits.messi, 'current', [97, 44, 86, 78], 0xffc43b),
  player('fw_cr7', 'C罗', 'FW', '前锋', 94, 'legend', '空中霸主', portraits.cr7, 'current', [96, 50, 88, 88], 0xffc43b),
  player('fw_vini', '维尼修斯', 'FW', '左锋', 93, 'purple', '边路爆破', portraits.vini, 'current', [91, 42, 97, 84], 0x9b45ff),
  player('fw_dembele', '登贝莱', 'FW', '边锋', 94, 'legend', '双足爆点', portraits.dembele, 'current', [94, 42, 96, 82], 0xffc43b),
  player('fw_salah', '萨拉赫', 'FW', '右锋', 92, 'purple', '内切射门', portraits.salah, 'current', [92, 45, 90, 86], 0x9b45ff),
  player('fw_kane', '凯恩', 'FW', '中锋', 91, 'purple', '支点射手', portraits.kane, 'current', [93, 52, 76, 88], 0x9b45ff),
  player('fw_yamal', '亚马尔', 'FW', '右锋', 90, 'purple', '灵巧突破', portraits.yamal, 'current', [88, 40, 92, 76], 0x9b45ff),
  player('fw_pele', '贝利', 'FW', '传奇前锋', 97, 'legend', '球王降临', portraits.pele, 'legend', [99, 48, 94, 88], 0xffc43b),
  player('fw_maradona', '马拉多纳', 'FW', '传奇前腰', 97, 'legend', '世纪盘带', portraits.maradona, 'legend', [98, 44, 91, 84], 0xffc43b),
  player('fw_ronaldo', '罗纳尔多', 'FW', '传奇中锋', 96, 'legend', '外星爆发', portraits.ronaldo, 'legend', [98, 46, 95, 82], 0xffc43b),
  player('fw_cruyff', '克鲁伊夫', 'FW', '传奇前锋', 94, 'legend', '全能指挥', portraits.cruyff, 'legend', [94, 58, 88, 86], 0xffc43b),
  player('fw_neymar', '内马尔', 'FW', '左锋', 92, 'purple', '桑巴魔术', portraits.neymar, 'current', [92, 44, 90, 76], 0x9b45ff),
  player('fw_son', '孙兴慜', 'FW', '边锋', 91, 'purple', '弧线爆射', portraits.son, 'current', [91, 50, 89, 86], 0x9b45ff),
  player('fw_griezmann', '格列兹曼', 'FW', '影锋', 90, 'purple', '灵动跑位', portraits.griezmann, 'current', [89, 58, 82, 86], 0x9b45ff),
  player('fw_suarez', '苏亚雷斯', 'FW', '中锋', 91, 'purple', '禁区嗅觉', portraits.suarez, 'current', [93, 56, 75, 82], 0x9b45ff),
  player('fw_lewandowski', '莱万多夫斯基', 'FW', '中锋', 92, 'purple', '冷静终结', portraits.lewandowski, 'current', [94, 54, 76, 84], 0x9b45ff),
  player('fw_benzema', '本泽马', 'FW', '中锋', 92, 'purple', '回撤串联', portraits.benzema, 'current', [92, 58, 78, 82], 0x9b45ff),
  player('fw_zlatan', '伊布', 'FW', '中锋', 91, 'purple', '霸王凌空', portraits.zlatan, 'legend', [93, 54, 72, 82], 0x9b45ff),
  player('fw_saka', '萨卡', 'FW', '右锋', 90, 'purple', '逆足内切', portraits.saka, 'current', [88, 54, 86, 88], 0x9b45ff),
  player('fw_lautaro', '劳塔罗', 'FW', '中锋', 91, 'purple', '禁区抢点', portraits.lautaro, 'current', [92, 58, 80, 88], 0x9b45ff),
  player('fw_osimhen', '奥斯梅恩', 'FW', '中锋', 91, 'purple', '冲刺头槌', portraits.osimhen, 'current', [92, 50, 92, 86], 0x9b45ff),
  player('fw_kvaratskhelia', '克瓦拉茨赫利亚', 'FW', '左锋', 90, 'purple', '变向突破', portraits.kvaratskhelia, 'current', [89, 42, 88, 82], 0x9b45ff),
  player('fw_nunez', '努涅斯', 'FW', '中锋', 88, 'gold', '冲刺压迫', portraits.nunez, 'current', [89, 48, 90, 86], 0x2f8cff),
  player('fw_leao', '莱奥', 'FW', '左锋', 90, 'purple', '大步突破', portraits.leao, 'current', [89, 40, 94, 82], 0x9b45ff),
  player('fw_pulisic', '普利西奇', 'FW', '边锋', 87, 'gold', '灵巧内切', portraits.pulisic, 'current', [86, 46, 88, 80], 0x2f8cff),
  player('fw_raphinha', '拉菲尼亚', 'FW', '右锋', 89, 'gold', '逆足兜射', portraits.raphinha, 'current', [88, 52, 87, 86], 0x2f8cff),
  player('fw_luis_diaz', '路易斯·迪亚斯', 'FW', '左锋', 89, 'gold', '边路撕扯', portraits.luisDiaz, 'current', [88, 54, 91, 88], 0x2f8cff),
  player('fw_isak', '伊萨克', 'FW', '中锋', 90, 'purple', '冷静推射', portraits.isak, 'current', [91, 44, 86, 82], 0x9b45ff),
  player('fw_vlahovic', '弗拉霍维奇', 'FW', '中锋', 88, 'gold', '强力终结', portraits.vlahovic, 'current', [90, 50, 78, 84], 0x2f8cff),
  player('fw_gakpo', '加克波', 'FW', '前锋', 88, 'gold', '斜插射门', portraits.gakpo, 'current', [87, 56, 84, 86], 0x2f8cff),
  player('fw_olise', '奥利塞', 'FW', '右锋', 88, 'gold', '左脚弧线', portraits.olise, 'current', [87, 42, 86, 80], 0x2f8cff),
  player('fw_nico_williams', '尼科·威廉姆斯', 'FW', '边锋', 88, 'gold', '高速变向', portraits.nicoWilliams, 'current', [86, 44, 94, 82], 0x2f8cff),
  player('fw_kubo', '久保建英', 'FW', '右锋', 87, 'gold', '小步盘带', portraits.kubo, 'current', [85, 46, 86, 82], 0x2f8cff),
  player('fw_mitoma', '三笘薫', 'FW', '左锋', 87, 'gold', '边线突破', portraits.mitoma, 'current', [86, 48, 88, 84], 0x2f8cff),

  player('mf_bellingham', '贝林厄姆', 'MF', '中场', 94, 'legend', '攻防全能', portraits.bellingham, 'current', [90, 84, 86, 92], 0xffc43b),
  player('mf_rodri', '罗德里', 'MF', '后腰', 93, 'purple', '中场屏障', portraits.rodri, 'current', [82, 94, 72, 90], 0x9b45ff),
  player('mf_debruyne', '德布劳内', 'MF', '中场', 92, 'purple', '精准直塞', portraits.debruyne, 'current', [90, 70, 76, 82], 0x9b45ff),
  player('mf_pedri', '佩德里', 'MF', '中场', 90, 'purple', '节奏大师', portraits.pedri, 'current', [84, 72, 82, 84], 0x9b45ff),
  player('mf_wirtz', '维尔茨', 'MF', '前腰', 91, 'purple', '灵动组织', portraits.wirtz, 'current', [88, 64, 84, 82], 0x9b45ff),
  player('mf_modric', '莫德里奇', 'MF', '中场', 90, 'purple', '外脚背传球', portraits.modric, 'current', [86, 72, 78, 78], 0x9b45ff),
  player('mf_zidane', '齐达内', 'MF', '传奇中场', 96, 'legend', '优雅掌控', portraits.zidane, 'legend', [94, 76, 80, 86], 0xffc43b),
  player('mf_xavi', '哈维', 'MF', '传奇中场', 94, 'legend', '控球核心', portraits.xavi, 'legend', [88, 78, 76, 88], 0xffc43b),
  player('mf_iniesta', '伊涅斯塔', 'MF', '传奇中场', 94, 'legend', '穿针引线', portraits.iniesta, 'legend', [90, 70, 82, 82], 0xffc43b),
  player('mf_ronaldinho', '小罗', 'MF', '传奇前腰', 95, 'legend', '魔幻盘带', portraits.ronaldinho, 'legend', [96, 50, 88, 80], 0xffc43b),
  player('mf_kimmich', '基米希', 'MF', '后腰', 90, 'purple', '精准调度', portraits.kimmich, 'current', [80, 86, 76, 92], 0x9b45ff),
  player('mf_foden', '福登', 'MF', '前腰', 90, 'purple', '小步摆脱', portraits.foden, 'current', [88, 62, 84, 84], 0x9b45ff),
  player('mf_musiala', '穆西亚拉', 'MF', '前腰', 91, 'purple', '灵蛇盘带', portraits.musiala, 'current', [90, 58, 87, 82], 0x9b45ff),
  player('mf_odegaard', '厄德高', 'MF', '前腰', 90, 'purple', '左脚指挥', portraits.odegaard, 'current', [87, 66, 78, 86], 0x9b45ff),
  player('mf_valverde', '巴尔韦德', 'MF', '中场', 90, 'purple', '高速推进', portraits.valverde, 'current', [84, 82, 88, 92], 0x9b45ff),
  player('mf_rice', '赖斯', 'MF', '后腰', 90, 'purple', '覆盖拦截', portraits.rice, 'current', [76, 88, 78, 92], 0x9b45ff),
  player('mf_gavi', '加维', 'MF', '中场', 88, 'gold', '贴身逼抢', portraits.gavi, 'current', [80, 78, 82, 90], 0x2f8cff),
  player('mf_enzo', '恩佐·费尔南德斯', 'MF', '中场', 88, 'gold', '长传调度', portraits.enzo, 'current', [82, 78, 76, 86], 0x2f8cff),
  player('mf_mac_allister', '麦卡利斯特', 'MF', '中场', 88, 'gold', '节奏串联', portraits.macAllister, 'current', [84, 76, 76, 88], 0x2f8cff),
  player('mf_bruno_fernandes', '布鲁诺·费尔南德斯', 'MF', '前腰', 90, 'purple', '冒险直塞', portraits.brunoFernandes, 'current', [89, 70, 76, 90], 0x9b45ff),
  player('mf_bernardo_silva', '贝尔纳多·席尔瓦', 'MF', '中场', 90, 'purple', '贴身控球', portraits.bernardoSilva, 'current', [86, 72, 82, 90], 0x9b45ff),
  player('mf_chiesa', '基耶萨', 'MF', '边前卫', 88, 'gold', '爆发前插', portraits.chiesa, 'current', [87, 56, 88, 82], 0x2f8cff),
  player('mf_barella', '巴雷拉', 'MF', '中场', 89, 'gold', '全场覆盖', portraits.barella, 'current', [82, 82, 80, 92], 0x2f8cff),
  player('mf_camavinga', '卡马文加', 'MF', '中场', 88, 'gold', '灵活扫荡', portraits.camavinga, 'current', [78, 84, 82, 88], 0x2f8cff),
  player('mf_tchouameni', '楚阿梅尼', 'MF', '后腰', 89, 'gold', '中路拦截', portraits.tchouameni, 'current', [76, 88, 76, 88], 0x2f8cff),

  player('df_vandijk', '范戴克', 'DF', '中卫', 92, 'purple', '防线统帅', portraits.vandijk, 'current', [58, 95, 78, 88], 0x9b45ff),
  player('df_saliba', '萨利巴', 'DF', '中卫', 90, 'purple', '冷静拦截', portraits.saliba, 'current', [52, 91, 82, 86], 0x9b45ff),
  player('df_hakimi', '阿什拉夫', 'DF', '边卫', 89, 'gold', '高速套边', portraits.hakimi, 'current', [72, 84, 94, 86], 0x2f8cff),
  player('df_dias', '鲁本·迪亚斯', 'DF', '中卫', 90, 'purple', '强硬对抗', portraits.dias, 'current', [50, 93, 70, 88], 0x9b45ff),
  player('df_maldini', '马尔蒂尼', 'DF', '传奇后卫', 96, 'legend', '完美站位', portraits.maldini, 'legend', [62, 98, 84, 90], 0xffc43b),
  player('df_carlos', '卡洛斯', 'DF', '传奇边卫', 93, 'legend', '重炮远射', portraits.carlos, 'legend', [84, 88, 94, 90], 0xffc43b),
  player('df_ramos', '拉莫斯', 'DF', '中卫', 91, 'purple', '铁血领袖', portraits.ramos, 'current', [66, 92, 76, 86], 0x9b45ff),
  player('df_trent', '阿诺德', 'DF', '右卫', 88, 'gold', '长传制导', portraits.trent, 'current', [78, 80, 82, 86], 0x2f8cff),
  player('df_davies', '阿方索·戴维斯', 'DF', '左卫', 88, 'gold', '极速回追', portraits.davies, 'current', [76, 80, 96, 84], 0x2f8cff),
  player('df_rudiger', '吕迪格', 'DF', '中卫', 90, 'purple', '强硬贴防', portraits.rudiger, 'current', [54, 92, 82, 88], 0x9b45ff),
  player('df_militao', '米利唐', 'DF', '中卫', 89, 'gold', '弹跳封堵', portraits.militao, 'current', [56, 90, 84, 86], 0x2f8cff),
  player('df_theo', '特奥', 'DF', '左卫', 90, 'purple', '边路冲刺', portraits.theo, 'current', [80, 82, 94, 88], 0x9b45ff),
  player('df_cancelo', '坎塞洛', 'DF', '边卫', 89, 'gold', '内收组织', portraits.cancelo, 'current', [82, 78, 84, 84], 0x2f8cff),
  player('df_kounde', '孔德', 'DF', '后卫', 89, 'gold', '边中皆宜', portraits.kounde, 'current', [58, 88, 84, 86], 0x2f8cff),
  player('df_upamecano', '于帕梅卡诺', 'DF', '中卫', 88, 'gold', '正面压迫', portraits.upamecano, 'current', [52, 89, 82, 86], 0x2f8cff),
  player('df_gvardiol', '格瓦迪奥尔', 'DF', '后卫', 89, 'gold', '左路推进', portraits.gvardiol, 'current', [70, 88, 84, 88], 0x2f8cff),
  player('df_kim_minjae', '金玟哉', 'DF', '中卫', 89, 'gold', '强力上抢', portraits.kimMinjae, 'current', [50, 90, 80, 88], 0x2f8cff),

  player('gk_courtois', '库尔图瓦', 'GK', '门将', 91, 'purple', '长臂神扑', portraits.courtois, 'current', [20, 94, 62, 82], 0x9b45ff),
  player('gk_donnarumma', '多纳鲁马', 'GK', '门将', 90, 'purple', '反应封堵', portraits.donnarumma, 'current', [18, 92, 66, 82], 0x9b45ff),
  player('gk_neuer', '诺伊尔', 'GK', '门将', 90, 'purple', '清道夫门将', portraits.neuer, 'current', [24, 91, 70, 78], 0x9b45ff),
  player('gk_buffon', '布冯', 'GK', '传奇门将', 95, 'legend', '传奇扑救', portraits.buffon, 'legend', [20, 97, 64, 86], 0xffc43b),
  player('gk_alisson', '阿利松', 'GK', '门将', 91, 'purple', '稳健出击', portraits.alisson, 'current', [22, 93, 68, 84], 0x9b45ff),
  player('gk_ederson', '埃德森', 'GK', '门将', 90, 'purple', '长传发动', portraits.ederson, 'current', [28, 90, 72, 84], 0x9b45ff),
  player('gk_casillas', '卡西利亚斯', 'GK', '传奇门将', 94, 'legend', '圣手反应', portraits.casillas, 'legend', [18, 96, 70, 84], 0xffc43b),
  player('gk_yashin', '雅辛', 'GK', '传奇门将', 96, 'legend', '黑衣传奇', portraits.yashin, 'legend', [18, 98, 68, 88], 0xffc43b),
  player('gk_maignan', '迈尼昂', 'GK', '门将', 89, 'gold', '快速下地', portraits.maignan, 'current', [20, 90, 70, 84], 0x2f8cff),
  player('gk_emiliano', '马丁内斯', 'GK', '门将', 89, 'gold', '点球心理', portraits.emiliano, 'current', [18, 91, 66, 84], 0x2f8cff),
  ...extraPlayers
];

export function drawCandidates(position: Position, excludeIds: string[] = []): PlayerCardData[] {
  const excluded = new Set(excludeIds);
  const pool = players.filter((player) => player.position === position && !excluded.has(player.id));
  return [...pool].sort(() => Math.random() - 0.5).slice(0, 3);
}

export const starterCollectionIds = starterPlayers.slice(0, 11).map((player) => player.id);

export const defaultCollectionIds = [
  ...starterCollectionIds,
  'st_gk_yu',
  'st_df_fang',
  'st_mf_ma',
  'st_fw_jiang',
  'fw_vini',
  'fw_salah',
  'fw_kane',
  'fw_yamal',
  'fw_son',
  'fw_griezmann',
  'fw_saka',
  'fw_lautaro',
  'fw_osimhen',
  'fw_nunez',
  'fw_leao',
  'fw_pulisic',
  'fw_raphinha',
  'fw_luis_diaz',
  'fw_isak',
  'fw_vlahovic',
  'fw_gakpo',
  'fw_olise',
  'fw_nico_williams',
  'fw_kubo',
  'fw_mitoma',
  'mf_rodri',
  'mf_pedri',
  'mf_wirtz',
  'mf_modric',
  'mf_kimmich',
  'mf_foden',
  'mf_musiala',
  'mf_odegaard',
  'mf_valverde',
  'mf_rice',
  'mf_gavi',
  'mf_enzo',
  'mf_mac_allister',
  'mf_bruno_fernandes',
  'mf_bernardo_silva',
  'mf_chiesa',
  'mf_barella',
  'mf_camavinga',
  'mf_tchouameni',
  'df_vandijk',
  'df_saliba',
  'df_hakimi',
  'df_dias',
  'df_ramos',
  'df_trent',
  'df_davies',
  'df_rudiger',
  'df_militao',
  'df_theo',
  'df_cancelo',
  'df_kounde',
  'df_upamecano',
  'df_gvardiol',
  'df_kim_minjae',
  'gk_courtois',
  'gk_donnarumma',
  'gk_neuer',
  'gk_alisson',
  'gk_ederson',
  'gk_maignan',
  'gk_emiliano',
  ...extraPlayerIds
];

export function rarityName(rarity: Rarity) {
  return rarityMeta[rarity].name;
}

export function playerPower(player?: PlayerCardData) {
  if (!player) return 0;
  return Math.round(player.rating * 0.72 + player.attack * 0.12 + player.defense * 0.1 + player.speed * 0.04 + player.stamina * 0.02);
}

export function drawScoutCandidates(collectionIds: string[], count = 3) {
  const owned = new Set(collectionIds);
  const pool = players.filter((player) => !owned.has(player.id) && !player.id.startsWith('st_'));
  const weights: Record<Rarity, number> = {
    bronze: 0,
    silver: 10,
    gold: 34,
    purple: 38,
    orange: 12,
    legend: 6
  };
  const result: PlayerCardData[] = [];

  while (result.length < count && result.length < pool.length) {
    const totalWeight = pool.reduce((sum, player) => {
      if (result.some((item) => item.id === player.id)) return sum;
      return sum + weights[player.rarity];
    }, 0);
    let roll = Math.random() * totalWeight;
    const picked = pool.find((player) => {
      if (result.some((item) => item.id === player.id)) return false;
      roll -= weights[player.rarity];
      return roll <= 0;
    });
    if (picked) result.push(picked);
  }

  if (result.length < count) {
    result.push(
      ...players
        .filter((player) => !result.some((item) => item.id === player.id))
        .sort((a, b) => b.rating - a.rating)
        .slice(0, count - result.length)
    );
  }

  return result;
}
